<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    //Symfony\Bundle\WebServerBundle\WebServerBundle::class => ['dev' => true],
    JMS\SerializerBundle\JMSSerializerBundle::class => ['all' => true],
    FOS\RestBundle\FOSRestBundle::class => ['all' => true],
    FOS\UserBundle\FOSUserBundle::class => ['all' => true],
    ZnBundle\Article\Symfony\ArticleBundle::class => ['all' => true],
    ZnBundle\Storage\Symfony\StorageBundle::class => ['all' => true],
    ZnSandbox\Sandbox\Messenger\Symfony\MessengerBundle::class => ['all' => true],
    ZnSandbox\Sandbox\Wsdl\Symfony\WsdlBundle::class => ['all' => true],
    ZnBundle\User\Symfony\UserBundle::class => ['all' => true],
    ZnBundle\Notify\Symfony\NotifyBundle::class => ['all' => true],
    ZnSandbox\Web\WebBundle::class => ['all' => true],
    ZnSandbox\Bundle\Admin\AdminBundle::class => ['all' => true],
    ZnSandbox\Sandbox\Dashboard\Symfony\DashboardBundle::class => ['all' => true],
];
