<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    //Symfony\Bundle\WebServerBundle\WebServerBundle::class => ['dev' => true],
    JMS\SerializerBundle\JMSSerializerBundle::class => ['all' => true],
    FOS\RestBundle\FOSRestBundle::class => ['all' => true],
    FOS\UserBundle\FOSUserBundle::class => ['all' => true],
    ZnBundle\Article\Symfony4\ArticleBundle::class => ['all' => true],
    ZnBundle\Storage\Symfony4\StorageBundle::class => ['all' => true],
    ZnSandbox\Sandbox\Messenger\Symfony\MessengerBundle::class => ['all' => true],
    ZnSandbox\Sandbox\Wsdl\Symfony\WsdlBundle::class => ['all' => true],
    ZnBundle\User\Symfony4\UserBundle::class => ['all' => true],
    ZnBundle\Notify\Symfony4\NotifyBundle::class => ['all' => true],
    ZnLib\Web\Symfony4\WebBundle\WebBundle::class => ['all' => true],
    ZnLib\Web\Symfony4\Admin\AdminBundle::class => ['all' => true],
    ZnBundle\Dashboard\Symfony4\DashboardBundle::class => ['all' => true],
];
