# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Migration,Tests,Bootstrap,Kernel.php}'

    ZnLib\Web\Symfony4\WebBundle\:
        resource: '../vendor/php7lab/web/src/*'
        exclude: '../vendor/php7lab/web/src/{Base}'

    ZnSandbox\Sandbox\:
        resource: '../vendor/php7lab/sandbox/src/*'
        exclude: '../vendor/php7lab/sandbox/src/{*/Yii,*/Domain/Migrations,*/Domain/Fixtures}'

    ZnBundle\Article\:
        resource: '../vendor/php7bundle/article/src/*'
        exclude: '../vendor/php7bundle/article/src/{*/Migrations,*/Fixtures}'

    ZnCrypt\Base\:
        resource: '../vendor/php7bundle/crypt/src/*'
        exclude: '../vendor/php7bundle/crypt/src/{*/Migrations,*/Fixtures}'

    ZnBundle\Notify\:
        resource: '../vendor/php7bundle/notify/src/*'
        exclude: '../vendor/php7bundle/notify/src/{*/Migrations,*/Fixtures}'

    ZnBundle\Queue\:
        resource: '../vendor/php7bundle/queue/src/*'
        exclude: '../vendor/php7bundle/queue/src/{*/Migrations,*/Fixtures}'

    ZnBundle\Reference\:
        resource: '../vendor/php7bundle/reference/src/*'
        exclude: '../vendor/php7bundle/reference/src/{*/Migrations,*/Fixtures}'

    ZnBundle\Storage\:
        resource: '../vendor/php7bundle/storage/src/*'
        exclude: '../vendor/php7bundle/storage/src/{*/Migrations,*/Fixtures}'

    ZnBundle\User\:
        resource: '../vendor/php7bundle/user/src/*'
        exclude: '../vendor/php7bundle/user/src/{*/Migrations,*/Fixtures}'

    ZnBundle\Article\Symfony4\Api\Controllers\ArticleController:
        tags: ['controller.service_arguments']

#    ZnBundle\Article\Symfony4\Web\Controllers\ArticleController:
#        tags: ['controller.service_arguments']

#    ZnSandbox\Bundle\:
#        resource: '../vendor/php7lab/bundle/src/*'
#        exclude: '../vendor/php7lab/bundle/src/{*/Yii,*/Migrations,*/Fixtures}'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

#    ZnBundle\Storage\Symfony4\Api\Controllers\FileController:
#        tags: ['controller.service_arguments']

    ZnBundle\Messenger\Symfony4\Api\Controllers\ChatController:
        tags: ['controller.service_arguments']

    ZnBundle\Messenger\Symfony4\Api\Controllers\MessageController:
        tags: ['controller.service_arguments']

    ZnBundle\Messenger\Symfony4\Web\Controllers\MessageController:
        tags: ['controller.service_arguments']

    ZnBundle\Messenger\Domain\Interfaces\ChatRepositoryInterface:
        class: ZnBundle\Messenger\Domain\Repositories\Eloquent\ChatRepository
        public: true

    ZnBundle\User\Domain\Interfaces\UserRepositoryInterface:
        class: ZnBundle\User\Domain\Repositories\Eloquent\UserRepository
        public: true

#    ZnSandbox\Sandbox\Bot\Symfony\Api\Controllers\ChatController:
#        tags: ['controller.service_arguments']

#    ZnBundle\Messenger\Symfony4\Web\Controllers\ChatController:
#        tags: ['controller.service_arguments']

#    ZnBundle\User\Symfony4\Api\Controllers\AuthController:
#        tags: ['controller.service_arguments']

#    ZnBundle\Queue\Symfony4\Commands\RunCommand:
#        tags: ['controller.service_arguments']

    ZnCore\Db\Helpers\Manager:
        arguments:
            $mainConfigFile: '%env(ELOQUENT_CONFIG_FILE)%'

    ZnTool\Package\Domain\Repositories\File\GroupRepository:
        arguments:
            $fileName: '%env(ELOQUENT_CONFIG_FILE)%'

    ZnLib\Rest\Symfony4\Controllers\ExceptionController:
        public: true
        arguments:
            $debug: '%kernel.debug%'

    ZnBundle\Notify\Domain\Interfaces\Repositories\EmailRepositoryInterface:
        class: ZnBundle\Notify\Domain\Repositories\Dev\EmailRepository
        public: true

    ZnSandbox\Sandbox\Dashboard\Domain\Interfaces\Services\DocServiceInterface:
        class: ZnSandbox\Sandbox\Dashboard\Domain\Services\DocService
        public: true

    ZnBundle\Messenger\Domain\Interfaces\Services\MessageServiceInterface:
        class: ZnBundle\Messenger\Domain\Services\MessageService
        public: true

    ZnBundle\Article\Domain\Interfaces\PostRepositoryInterface:
        class: ZnBundle\Article\Domain\Repositories\Eloquent\PostRepository
        public: true

#    ZnCrypt\Jwt\Domain\Interfaces\Services\JwtServiceInterface:
#            class: ZnCrypt\Jwt\Domain\Services\JwtService
#            public: true
