connection:
#    map:
#        article_category: art_category
#        article_post: art_post
#        article_tag: art_tag
#        article_tag_post: art_tag_post
#        eq_migration: migration
#        storage_service: storage_service
#        storage_file: storage_file

#        defaultConnection: mysqlServer
#        defaultConnection: sqliteServer
#    defaultConnection: pgsqlServer
#    connections:
#        mysqlServer:
#            driver: mysql
#            host: localhost
#            database: symfony-tpl
#            username: root
#        pgsqlServer:
#            driver: pgsql
#            host: localhost
#            database: symfony-tpl
#            username: postgres
#            password: postgres
#        sqliteServer:
#            driver: sqlite
#            database: /var/sqlite/default.sqlite
fixture:
    directory:
#        - /src/Fixtures
        - /vendor/php7bundle/article/src/Domain/Fixtures
        - /vendor/php7bundle/user/src/Domain/Fixtures
#        - /vendor/php7bundle/storage/src/Domain/Fixtures
#        - /vendor/php7lab/sandbox/src/Messenger/Domain/Fixtures
        - /vendor/php7lab/sandbox/src/Bot/Domain/Fixtures
migrate:
    directory:
        - /vendor/php7bundle/article/src/Domain/Migrations
        - /vendor/php7bundle/user/src/Domain/Migrations
        - /vendor/php7bundle/queue/src/Domain/Migrations
        - /vendor/php7bundle/storage/src/Domain/Migrations
        - /vendor/php7lab/sandbox/src/Messenger/Domain/Migrations
        - /vendor/php7lab/sandbox/src/Bot/Domain/Migrations
